<!--修改密码 modal-->
<div class="modal-dialog modal fade" id="globalEditPasswordModal" tabindex="-1" role="globalEditPasswordModal">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" >修改密码</h4>
        </div>
        <div class="modal-body">
            <form>
                <div class="form-group">
                    <label for="recipient-name" class="control-label">原密码:</label>
                    <input type="password" class="form-control" id="gepm-opass">
                </div>
                <div class="form-group">
                    <label for="message-text" class="control-label">新密码:</label>
                    <input type="password" class="form-control" id="gepm-npass">
                </div>
                <div class="form-group">
                    <label for="message-text" class="control-label">确认密码:</label>
                    <input type="password" class="form-control" id="gepm-rpass">
                </div>

            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-primary" id="gepm-confirm">保存</button>
        </div>
    </div>
</div>
