<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box black ">
                <div class="portlet-title ">
                    <div class="caption">
                        <!--        <i class="fa fa-globe"></i>-->
                        企业管理
                    </div>
                    <div class="actions">
                        <a href="javascript:;" class="btn btn-default btn-sm js_edit">
                            <i class="fa fa-pencil"></i> 添加企业
                        </a>
                    </div>
                </div>
                <div class="portlet-body" style="overflow: auto">
<!--                    <div class="table-toolbar">-->
<!--                        <div class="row">-->
<!--                            <div class="col-md-6">-->
<!--                                <div class="btn-group">-->
<!--                                    <button class="btn green js_edit" >-->
<!--                                        添加企业  <i class="fa fa-plus"></i>-->
<!--                                    </button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
                    <table class="table table-striped table-bordered table-hover " id="sample_1">
                        <thead>
                        <tr>
                            <th class="min-width-100">企业名称</th>
                            <th class="min-width-100">认证域名</th>
                            <th class="min-width-100">权限列表</th>
                            <th class="min-width-100">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $list=$this->list;
                        if(!empty($list))
                        {
                            $str='';
                            foreach($list as $v)
                            {
                                $pStr='';
                                if(!empty($v['privileges']) && is_array($v['privileges']))
                                {
                                    foreach($v['privileges'] as $p)
                                    {
                                        $pStr.=" <span data-id='{$p['id']}' data-json='".json_encode($p)."' class='display-inline-block margin-5 btn label label-primary'>{$p['name']}</span>";
                                    }
                                }

                                $str.="
                                <tr class='odd gradeX'>
                                    <td>{$v['name']}</td>
                                    <td>{$v['domain']}</td>
                                    <td> {$pStr}</td>
                                    <td>
                                        <button type='button' class='btn margin-5 blue js_edit' data-id='{$v['id']}' data-edit='1' data-info='".json_encode($v)."' >修改</button>
                                        <button type='button' class='btn margin-5 green js_set_super_admin' data-is-super-admin='{$v['is_super_admin']}' data-id='{$v['id']}'>".($v['is_super_admin']==0?'设置超级企业':'取消超级企业')."</button>
                                        <button type='button' class='btn margin-5 red js_delete' data-id='{$v['id']}'>删除</button>
                                    </td>
                                </tr>";
                            }
                            echo $str;
                        }
                        ?>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
</div>

<!--修改用户信息modal-->
<div class="modal fade modal-scroll" id="editModal" role="editModal" >
    <div class="modal-content" >
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" >添加</h4>
        </div>
        <div class="modal-body">
            <form>
                <div class="form-group">
                    <label for="eui-name" class="control-label">企业名称:</label>
                    <input type="text" class="form-control" id="eui-name">
                </div>
                <div class="form-group">
                    <label for="eui-domain" class="control-label">认证域名:</label>
                    <input type="text" class="form-control" id="eui-domain">
                </div>
                <hr>
                <h4>选择权限</h4>
                <div id='eui-privilege'>
                    <?php
                    $privilegeList=$this->privilegeList;
                    if(!empty($privilegeList))
                    {
                        $str2='';
                        foreach($privilegeList as $v2)
                        {
                            $subArrHtml='';
                            if($v2['subArr'] && is_array($v2['subArr']))
                            {
                                foreach($v2['subArr'] as $sbv)
                                {
                                    $subArrHtml.="
                                   <div class='md-checkbox'>
                                        <input type='checkbox' id='checkbox_{$sbv['id']}' value='{$sbv['id']}' data-id='{$sbv['id']}' data-name={$sbv['name']} class='md-check'>
                                        <label for='checkbox_{$sbv['id']}'>
                                            <span class='inc'></span>
                                            <span class='check'></span>
                                            <span class='box'></span>
                                            {$sbv['name']}
                                        </label>
                                    </div>";
                                }
                            }

                            $str2.="
                             <div class='form-group form-md-checkboxes'>
                                <label>{$v2['name']}</label>
                                <div class='md-checkbox-inline' >
                                    {$subArrHtml}
                                </div>
                            </div>
                            ";

                        }
                        echo $str2;
                    }
                    ?>
                </div>

            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-primary" id="eui-confirm">提交</button>

        </div>
    </div>
</div>
