<div class="page-content">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-list"></i>用户反馈
            </div>
            <div class="tools">
                <a href="javascript:;" class="reload"></a>
            </div>
        </div>
        <div class="portlet-body">
            <table class="table table-striped table-bordered table-hover" id="feedbackTable">
                <thead>
                <tr>
                    <th style="width: 10%">用户名</th>
                    <th style="width: 13%">手机号</th>
                    <th>内容</th>
                    <th style="width: 15%">反馈时间</th>
                    <th style="width: 7%">状态</th>
                    <th style="width: 20%">操作</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal-dialog modal fade modal-scroll" id="feedbackReplay" tabindex="-1"  >
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title">回复用户</h4>
        </div>
        <div class="modal-body">
            <div class="portlet-body">
                <div class="form-body">
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <textarea class="form-control inputContent" rows="3"></textarea>
                        <label for="form_control_1">内容</label>
                        <span class="help-block">请输入回复内容</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn default cancel_button" data-dismiss="modal">取消</button>
            <button type="button" class="btn blue submit">提交</button>
        </div>
    </div>
</div>

<!--查看回复-->
<div class="modal fade modal-scroll" id="replayInfo" >
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="exampleModalLabel">回复列表</h4>
        </div>
        <div class="modal-body">
            <div class="portlet-body form">
                <table class="table table-striped table-bordered table-hover " id="replyTable" >
                    <thead>
                    <tr>
                        <th>操作人账号</th>
                        <th>操作人姓名</th>
                        <th>回复内容</th>
                        <th>回复时间</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-primary" data-dismiss="modal">确定</button>
        </div>
    </div>
</div>