<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box black">
                <div class="portlet-title ">
                    <div class="caption">
                        <!--        <i class="fa fa-globe"></i>-->
                        权限管理
                    </div>
                    <div class="actions">
                        <a href="javascript:;" class="btn btn-default btn-sm js_edit">
                            <i class="fa fa-pencil"></i> 添加模块
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
<!--                    <div class="table-toolbar">-->
<!--                        <div class="row">-->
<!--                            <div class="col-md-6">-->
<!--                                <div class="btn-group">-->
<!--                                    <button  class="btn green js_edit" >-->
<!--                                        添加  <i class="fa fa-plus"></i>-->
<!--                                    </button>-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                    </div>-->
                    <table class="table table-striped table-bordered table-hover" id="sample_1">
                        <thead>
                        <tr>
                            <th class="min-width-100">action</th>
                            <th class="min-width-100">模块名</th>
                            <th class="min-width-100">子模块</th>
                            <th class="min-width-100">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $list=$this->list;
                        if(!empty($list))
                        {
                            $str='';
                            foreach($list as $v)
                            {
                                $childrenHtml='';
                                if($v['subArr'] && is_array($v['subArr']))
                                {
                                    foreach($v['subArr'] as $v2)
                                    {
                                        $childrenHtml.="
                                            <span class='display-inline-block margin-5 btn label label-info'>{$v2['name']}</span>
                                        ";
                                    }
                                }
                                $str.="
                                <tr class='odd gradeX'>
                                    <td>{$v['action']}</td>
                                    <td> {$v['name']}</td>
                                    <td>{$childrenHtml} </td>
                                    <td>
                                        <button type='button' class='margin-5 btn blue js_edit' data-id='{$v['id']}' data-edit='1' data-info='".json_encode($v)."' data-toggle='modal' >修改</button>
                                        <button type='button' class='margin-5 btn red js_delete' data-id='{$v['id']}'>删除</button>
                                    </td>
                                </tr>";
                            }
                            echo $str;
                        }
                        ?>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
</div>

<!--修改用户信息modal-->

<div class="modal fade modal-scroll" id="editModal" tabindex="-1" >
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" >添加权限</h4>
        </div>
        <div class="modal-body">
            <form>
                <div class="form-group">
                    <label for="recipient-name" class="control-label">action:</label>
                    <input type="text" class="form-control" id="eui-action">
                </div>
                <div class="form-group">
                    <label for="message-text" class="control-label">模块名:</label>
                    <input type="text" class="form-control" id="eui-name">
                </div>

                <hr>
                <div class="form-group form-inline">
                    <label class="control-label margin-right-10"><h4>子模块管理</h4></label>
                    <button type="button" class="btn green" id="eui_add_item">新增项目<i class="fa fa-plus"></i></button>
                </div>
                <div class="eui_item_list">
                    <div class="form-group form-inline eui_item">
                        <input type="text" class="form-control eui_item_action"  placeholder="请输入子action">
                        <input type="text" class="form-control eui_item_name" placeholder="请输入子模块名">
                        <button type="button" class="btn red eui_del_item" >删除</button>
                    </div>
                </div>
                <!--      模板          -->
                <div class="display-none eui_item_template">
                    <div class="form-group form-inline  eui_item">
                        <input type="text" class="form-control eui_item_action"  placeholder="请输入子action">
                        <input type="text" class="form-control eui_item_name" placeholder="请输入子模块名">
                        <button type="button" class="btn red eui_del_item" >删除</button>
                    </div>
                </div>
            </form>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-primary" id="eui-confirm">提交</button>
        </div>
    </div>
</div>
