<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box black">
                <div class="portlet-title ">
                    <div class="caption">
                        <!--        <i class="fa fa-globe"></i>-->
                        角色管理
                    </div>
                    <div class="actions">
                        <a href="javascript:;" class="btn btn-default btn-sm js_edit">
                            <i class="fa fa-pencil"></i> 添加角色
                        </a>
                        <?php
                        $companyList=$this->companyList;
                        $companyHtml="<li ><a href='/account/role'> 所有公司</a></li>";
                        $currentCompany='选择企业';
                        if($companyList && is_array($companyList))
                        {
                            foreach($companyList as $clv)
                            {
                                $active='';
                                if($_GET['cid']==$clv['id'])
                                {
                                    $active='active';
                                    $currentCompany=$clv['name'];
                                }
                                $companyHtml.="
                            <li class='{$active}'><a href='/account/role?cid={$clv['id']}'> {$clv['name']}</a></li>
                        ";
                            }
                        }
                        $cBodyHtml="
                         <div class='btn-group'>
                            <a class='btn btn-default btn-sm' href='javascript:;' data-toggle='dropdown'>
                                <i class='fa  fa-align-justify'></i> {$currentCompany} <i class='fa fa-angle-down'></i>
                            </a>
                            <ul class='dropdown-menu pull-right'>
                                {$companyHtml}
                            </ul>
                        </div>
                        ";
                        if($this->accessStatus)
                        {
                            echo $cBodyHtml;
                        }
                        ?>
                    </div>
                </div>

                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_1">
                        <thead>
                        <tr>
                            <th class="min-width-100">角色</th>
                            <th class="min-width-100">权限列表</th>
                            <th class="min-width-100">所属企业</th>
                            <th class="min-width-100">操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        $list=$this->list;
                        if(!empty($list))
                        {
                            $str='';
                            foreach($list as $v)
                            {
                                $pStr='';
                                if(!empty($v['privileges']) && is_array($v['privileges']))
                                {
                                    foreach($v['privileges'] as $p)
                                    {
                                        $pStr.=" <span data-id='{$p['id']}' data-json='".json_encode($p)."' class='label margin-5 display-inline-block label-primary'>{$p['name']}</span>";
                                    }
                                }

                                $str.="
                                <tr class='odd gradeX'>
                                    <td>{$v['name']}</td>
                                    <td> {$pStr}</td>
                                    <td> ".($v['company_name']?$v['company_name']:'无')."</td>
                                    <td>
                                        <button type='button' class='btn margin-5 blue js_edit' data-id='{$v['id']}' data-edit='1' data-info='".json_encode($v)."' >修改</button>
                                        <button type='button' class='btn margin-5 red js_delete' data-id='{$v['id']}'>删除</button>
                                    </td>
                                </tr>";
                            }
                            echo $str;
                        }
                        ?>

                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
</div>

<!--修改用户信息modal-->
<div class="modal fade modal-scroll" id="editModal" role="editModal">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" >添加权限</h4>
        </div>
        <div class="modal-body">
            <form>
                <div class="form-group">
                    <label for="eui-name" class="control-label">角色:</label>
                    <input type="text" class="form-control" id="eui-name">
                </div>
                <hr>
                <h4>选择权限</h4>
                <div id='eui-privilege'>
                    <?php
                    $privilegeList=$this->privilegeList;
                    if(!empty($privilegeList))
                    {
                        $str2='';
                        foreach($privilegeList as $v2)
                        {
                            $subArrHtml='';
                            if($v2['subArr'] && is_array($v2['subArr']))
                            {
                                foreach($v2['subArr'] as $sbv)
                                {
                                    $subArrHtml.="
                                   <div class='md-checkbox'>
                                        <input type='checkbox' id='checkbox_{$sbv['id']}' value='{$sbv['id']}' data-id='{$sbv['id']}' data-name={$sbv['name']} class='md-check'>
                                        <label for='checkbox_{$sbv['id']}'>
                                            <span class='inc'></span>
                                            <span class='check'></span>
                                            <span class='box'></span>
                                            {$sbv['name']}
                                        </label>
                                    </div>";
                                }
                            }

                            $str2.="
                             <div class='form-group form-md-checkboxes'>
                                <label>{$v2['name']}</label>
                                <div class='md-checkbox-inline' >
                                    {$subArrHtml}
                                </div>
                            </div>
                            ";

                        }
                        echo $str2;
                    }
                    ?>
                </div>

            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-primary" id="eui-confirm">提交</button>

        </div>
    </div>
</div>
