<div class="page-content">
    <div class="row">
    <div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box black">
    <div class="portlet-title ">
        <div class="caption">
    <!--        <i class="fa fa-globe"></i>-->
            用户管理
        </div>
        <div class="actions">
            <a href="javascript:;" class="btn btn-default btn-sm js_edit">
                <i class="fa fa-pencil"></i>
                添加用户
            </a>
            <?php
                $companyList=$this->companyList;
                $companyHtml="<li ><a href='/account/user'> 所有公司</a></li>";
                $currentCompany='选择企业';
                if($companyList && is_array($companyList))
                {
                    foreach($companyList as $clv)
                    {
                        $active='';
                        if($_GET['cid']==$clv['id'])
                        {
                            $active='active';
                            $currentCompany=$clv['name'];
                        }
                        $companyHtml.="
                            <li class='{$active}'><a href='/account/user?cid={$clv['id']}'> {$clv['name']}</a></li>
                        ";
                    }
                }
                $cBodyHtml="
                 <div class='btn-group'>
                    <a class='btn btn-default btn-sm' href='javascript:;' data-toggle='dropdown'>
                        <i class='fa  fa-align-justify'></i> {$currentCompany} <i class='fa fa-angle-down'></i>
                    </a>
                    <ul class='dropdown-menu pull-right'>
                        {$companyHtml}
                    </ul>
                </div>
                ";
                if($this->accessStatus)
                {
                    echo $cBodyHtml;
                }
            ?>
        </div>
    </div>
    <div class="portlet-body">

    <table class="table table-striped table-bordered table-hover"   id="account_table_1">
    <thead>
        <tr>
            <th>账号</th>
            <th>姓名</th>
            <th>手机</th>
            <th>所属企业</th>
            <th>角色</th>
            <th>创建时间</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
    <?php
        $list=$this->list;
        if(!empty($list))
        {
            $str='';
            foreach($list as $v)
            {
                $roleHtml='';
                $actionHtml='';
                if($v['is_admin']==1)
                {
                    $roleHtml="<span class='label label-danger'>企业管理员</span>";
                }
                else
                {
                    $roleHtml="<span class='label label-success'>{$v['role_name']}</span>";
                    if($this->cid==$v['cid'])
                    {
                        $actionHtml="
                         <button type='button' class='btn margin-5 blue js_edit' data-json='".json_encode($v)."' data-edit='1'  >修改</button>
                         <button type='button' class='btn margin-5 red js_delete' data-id='{$v['id']}'>删除</button>
                        ";
                    }

                }
                $str.="
                <tr class='odd gradeX'>
                    <td>{$v['account']}</td>
                    <td> {$v['name']}</td>
                    <td>{$v['phone']}</td>
                    <td>".($v['company_name']?$v['company_name']:'无')."</td>
                    <td>{$roleHtml}</td>
                    <td class='center'>".date('Y-m-d H:i:s',$v['time'])."</td>
                    <td>
                        {$actionHtml}
                    </td>
                </tr>";
            }
            echo $str;
        }
    ?>

    </tbody>
    </table>
    </div>
    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
    </div>
    </div>
</div>

<!--修改用户信息modal-->
<div class="modal fade modal-scroll" id="editUserInfoModal" >
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="exampleModalLabel">添加用户</h4>
        </div>
        <div class="modal-body">
            <form>
                <div class="form-group">
                    <label for="recipient-name" class="control-label">账号(邮箱):</label>
                    <input type="text" class="form-control" id="eui-account">
                </div>
                <div class="form-group">
                    <label for="message-text" class="control-label">密码:</label>
                    <input type="password" class="form-control" id="eui-password">
                </div>
                <div class="form-group">
                    <label for="message-text" class="control-label">姓名:</label>
                    <input type="text" class="form-control" id="eui-name">
                </div>
                <div class="form-group">
                    <label for="message-text" class="control-label">电话:</label>
                    <input type="text" class="form-control" id="eui-mobile">
                </div>
                <div class="form-group form-md-radios">
                    <label>选择角色：</label>
                    <div class="md-radio-inline" id="eui-role">
                        <?php
                            $roleList=$this->roleList;
                            if(!empty($roleList))
                            {
                                $str='';
                                foreach($roleList as $v2)
                                {
                                    $str.="
                                     <div class='md-radio'>
                                        <input type='radio' id='radio_{$v2['id']}' value='{$v2['id']}' data-name='{$v2['name']}' name='role' class='md-radiobtn'>
                                        <label for='radio_{$v2['id']}'>
                                            <span class='inc'></span>
                                            <span class='check'></span>
                                            <span class='box'></span>
                                            {$v2['name']} </label>
                                    </div>
                                    ";
                                }
                                echo $str;
                            }
                        ?>

                    </div>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
            <button type="button" class="btn btn-primary" id="eui-confirm">提交</button>
        </div>
    </div>
</div>
