<div class="page-content">
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box black">
                <div class="portlet-title ">
                    <div class="caption">
                        <!--        <i class="fa fa-globe"></i>-->
                        操作日志
                    </div>
                    <div class="actions">
<!--                        <a href="javascript:;" class="btn btn-default btn-sm js_edit">-->
<!--                            <i class="fa fa-pencil"></i> 添加管理员-->
<!--                        </a>-->
                    </div>
                </div>
                <div class="portlet-body" >
                    <div class="row form-group">
                        <div class="col-md-4">
                            <label class="control-label">选择时间</label>
                            <div class="input-icon">
                                <i class="fa fa-calendar"></i>
                                <input id="search_time"  class="form-control date-picker" size="16" type="text" value="<?php echo date('Y-m-d')?>" data-date-format="yyyy-mm-dd"/>
                            </div>
                        </div>

                        <div class="col-md-2">
                            <label class="control-label">&nbsp;</label>
                            <div class="input-icon">
                                <button id="search_submit" class="btn blue btn-block ">搜索 <i class="m-icon-swapright m-icon-white"></i></button>
                            </div>
                        </div>
                    </div>
                    <table class="table table-striped table-bordered table-hover" id="operation_table">
                        <thead>
                        <tr>
                            <th class="min-width-100">账号</th>
                            <th class="min-width-100">姓名</th>
                            <th class="min-width-100">访问ip</th>
                            <th class="min-width-100">操作类型</th>
                            <th class="min-width-100">操作描述</th>
                            <th class="min-width-100">操作时间</th>
                        </tr>
                        </thead>
                        <tbody id="operation_table_list">


                        </tbody>
                    </table>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
</div>

