<div class="page-content">

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN ROW -->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN CHART PORTLET-->
                    <div class="portlet light bordered">
                        <div class="portlet-title">
                            <div class="caption caption-md">
                                <i class="icon-bar-chart font-green-haze hide"></i>
                                <span class="caption-subject font-green-haze bold uppercase">
                                    申请试用
                                </span>
                            </div>
                            <div class="actions fr">

                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row form-group">
                                <div class="col-md-6">
                                    <label class="control-label">&nbsp;</label>
                                    <div class="input-icon">
                                        <div class="input-group  date-picker input-daterange" data-date="" data-date-format="yyyy-mm-dd">
                                            <input type="text" id="start_search_time" class="form-control " name="from" value="<?php echo date('Y-m-d',strtotime('-7 day'));?>">
                                            <span class="input-group-addon">至</span>
                                            <input type="text" id="end_search_time" class="form-control " name="to" value="<?php echo date('Y-m-d',strtotime('0 day'));?>">
                                        </div>
                                        <!-- /input-group -->
                                        <span class="help-block"></span>
                                    </div>
                                </div>


                                <div class="col-md-2">
                                    <label class="control-label">&nbsp;</label>
                                    <div class="input-icon">
                                        <button id="search_submit" class="btn blue btn-block ">搜索 <i class="m-icon-swapright m-icon-white"></i></button>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="portlet-body" id="wrapperPageList">
                            <div>
                                <table class="table table-striped table-bordered table-hover js_table_list" align="center">
                                    <thead>
                                    <tr>
                                        <th class="min-width-100">姓名</th>
                                        <th class="min-width-100">邮箱</th>
                                        <th class="min-width-100">电话</th>
                                        <th class="min-width-100">公司名称</th>
                                        <th class="min-width-100">试用产品</th>
                                        <th class="min-width-100">软件类别</th>
                                        <th class="min-width-100">申请时间</th>
                                        <th >操作</th>
                                    </tr>
                                    </thead>
                                    <tbody id="list">
                                    <?php echo $this->html;?>
                                    </tbody>
                                </table>
                                <div id='list_count' class="gone"></div>
                                <?php echo BaseBuilder::createPageIndicator();?>
                            </div>

                        </div>
                    </div>
                    <!-- END CHART PORTLET-->

                </div>
            </div>
            <!-- END ROW -->

        </div>
    </div>
</div>


<div class="modal-dialog modal fade modal-scroll" id="editOrAddModal" tabindex="-1"  >
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title" data-new="添加" data-edit="编辑"></h4>
        </div>
        <div class="modal-body ">
            <div class="form-group">
                <label for="message-text" class="control-label">留言内容</label>
                <textarea id="js_modal_content" disabled class="form-control" rows="10"></textarea>
            </div>

        </div>
        <div class="modal-footer">

            <!--            <button type="button" class="btn default cancel_button" data-dismiss="modal">取消</button>-->
            <button type="button" class="btn blue submit" data-dismiss="modal">确定</button>
        </div>
    </div>
</div>
