<div class="page-content">
    <div class="portlet box black">
        <div class="portlet-title">
            <div class="caption">
                资质和产权
            </div>
            <div class="tools">

            </div>
            <div class="actions">
                <a href="javascript:;" class="btn btn-default btn-sm js_edit js_new_btn ">
                    <i class="fa fa-plus"></i>
                    添加
                </a>
                <a href="javascript:;" class="btn btn-default btn-sm js_sort_save">
                    <i class="fa fa-save"></i> 保存排序
                </a>
            </div>
        </div>

        <div class="portlet-body" id="wrapperPageList">
            <div class="tabbable-line">
                <ul class="nav nav-tabs">
                    <li class="fr active" data-id="0">
                        <a href="#" data-toggle="tab" aria-expanded="false">知识产权</a>
                    </li>
                    <li class="fr " data-id="1">
                        <a href="#" data-toggle="tab" aria-expanded="true">公司资质</a>
                    </li>

                </ul>

            </div>

            <div class="table-scrollable" >
                <table class="table table-striped table-bordered table-hover table-middle" align="center">
                    <thead>
                    <tr>
                        <th class="min-width-100">图片</th>
                        <th class="min-width-100">描述</th>
                        <th class="min-width-100">排序</th>
                        <th >操作</th>
                    </tr>
                    </thead>
                    <tbody class="js_table_list" id="list">
                    <?php echo $this->html;?>
                    </tbody>
                </table>
            </div>
            <div id='list_count' class="gone"></div>
            <?php echo BaseBuilder::createPageIndicator();?>
        </div>
    </div>
</div>


<div class="modal-dialog modal fade modal-scroll" id="editOrAddModal" tabindex="-1"  data-width="80%">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title" data-new="添加" data-edit="编辑"></h4>
        </div>
        <div class="modal-body ">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label">描述</label>
                        <input type="text" id="js_modal_name" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-10">
                    <div class="form-group">
                        <label for="message-text" class="control-label">图片</label>
                        <input type="text" class="form-control " id="js_modal_pic">
                        <div class="col-md-12" >
                            <img class="js_modal_pic_preview img-preview gone " src="" >
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label for="message-text" class="control-label">&nbsp;</label>
                        <button type="button" class="js_upload_image btn default form-control" data-id="js_upload_image">上传</button>
                    </div>
                </div>
            </div>


        </div>
        <div class="modal-footer">
            <button type="button" class="btn default js_cancel" data-dismiss="modal">取消</button>
            <button type="button" class="btn blue js_submit">提交</button>
        </div>
    </div>
</div>


<div class="modal-dialog modal fade modal-scroll" id="uploadAppProgressModal" tabindex="-1"  >
    <div class="modal-content">
        <div class="modal-header">
            <!--            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>-->
            <h4 class="modal-title" data-new="" data-edit="">上传中</h4>
        </div>
        <div class="modal-body ">
            <div class="form-group">
                <div class=" js_progress_section">
                    <p class="size">当前进度</p>
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
