<div class="page-content">
    <div class="portlet box black">
        <div class="portlet-title">
            <div class="caption">
                菜单管理
            </div>
            <div class="tools">

            </div>
            <div class="actions">
                <a href="javascript:;" class="btn btn-default btn-sm js_edit js_new_btn ">
                    <i class="fa fa-plus"></i>
                    添加菜单
                </a>
                <a href="javascript:;" class="btn btn-default btn-sm js_sort_save">
                    <i class="fa fa-save"></i> 保存排序
                </a>
            </div>
        </div>
        <div class="portlet-body" id="wrapperPageList">
            <div class="tabbable-line">
                <ul class="nav nav-tabs">
                    <li class="fr active" data-id="0">
                        <a href="#" data-toggle="tab" aria-expanded="false">导航栏</a>
                    </li>
                    <li class="fr " data-id="1">
                        <a href="#" data-toggle="tab" aria-expanded="true">网站地图</a>
                    </li>

                </ul>

            </div>

            <div class="table-scrollable" >
                <table class="table table-striped table-bordered table-hover table-middle" align="center">
                    <thead>
                    <tr>
                        <th class="min-width-100">标题</th>
                        <th class="min-width-100">菜单类型</th>
                        <th class="min-width-100">排序</th>
                        <th >操作</th>
                    </tr>
                    </thead>
                    <tbody class="js_table_list" id="list">
                        <?php echo $this->html;?>
                    </tbody>
                </table>
            </div>
            <div id='list_count' class="gone"></div>
            <?php echo BaseBuilder::createPageIndicator();?>
        </div>
    </div>
</div>


<div class="modal-dialog modal fade modal-scroll" id="editOrAddModal" tabindex="-1"  data-width="80%">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title" data-new="添加" data-edit="编辑"></h4>
        </div>
        <div class="modal-body ">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label">菜单名称</label>
                        <input type="text" id="js_modal_name" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="col-md-6 js_modal_type_sec">
                    <div class="form-group">
                        <label class="control-label">菜单类型</label>
                        <select class="form-control" id="js_modal_type">
                            <option value="1">一级菜单</option>
                            <option value="2">二级菜单</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6 ">
                    <div class="form-group">
                        <label class="control-label" >target</label>
                        <select class="form-control" id="js_modal_target" >
                            <option value="_self">_self</option>
                            <option value="_blank">_blank</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-12 js_modal_parent_section gone">
                    <div class="form-group">
                        <label class="control-label">父级菜单</label>
                        <select class="form-control" id="js_modal_parent" >
                            <option value="0">请选择父级菜单</option>
                            <?php
                                $subMenus = $this->subMenus;
                                $pageOptionsHtml = '';
                                foreach ($subMenus as $subMenu)
                                {
                                    $id= $subMenu['id'];
                                    $name= $subMenu['name'];
                                    $pageOptionsHtml.="
                                            <option value={$id}>{$name}</option>
                                            ";
                                }
                                echo $pageOptionsHtml;
                            ?>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">链接类型</label>
                        <div class="form-md-radios">
                            <!--                                <label>Checkboxes</label>-->
                            <div class="md-radio-inline">
                                <div class="md-radio">
                                    <input type="radio" id="radio_type_0" data-id=".js_modal_url_section" name="radio_type" class="md-radiobtn js_radio_btn_type" value="0">
                                    <label for="radio_type_0">
                                        <span class="inc"></span>
                                        <span class="check"></span>
                                        <span class="box"></span>
                                        自定义
                                    </label>
                                </div>
                                <div class="md-radio">
                                    <input type="radio" id="radio_type_1" data-id=".js_modal_page_section" name="radio_type" class="md-radiobtn js_radio_btn_type" value="1">
                                    <label for="radio_type_1">
                                        <span class="inc"></span>
                                        <span class="check"></span>
                                        <span class="box"></span>
                                        单页选择
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 js_modal_show_type_sec gone">
                    <div class="form-group">
                        <label class="control-label">展现形式</label>
                        <select class="form-control" id="js_modal_show_type">
                            <option value="0">折叠</option>
                            <option value="1">伸展</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-12 js_modal_url_section js_radio_target_section">
                    <div class="form-group">
                        <label class="control-label"></label>
                        <input type="text" id="js_modal_url" class="form-control" placeholder="链接地址">
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="col-md-12 js_modal_page_section js_radio_target_section">
                    <div class="form-group">
                        <label class="control-label"></label>
                        <select class="form-control" id="js_modal_page">
                            <?php
                                $options = $this->pageOptions;
                                $pageOptionsHtml = '';

                                foreach ($options as $option)
                                {
                                    $id= $option['id'];
                                    $name= $option['name'];
                                    $pageOptionsHtml.="
                                        <option value={$id}>{$name}</option>
                                        ";
                                }
                                echo $pageOptionsHtml;
                            ?>
                        </select>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 clear-fix" style="height: 50px;">
                    子菜单
                    <button type="button" class="btn fr green btn-sm js_modal_params_add_btn min-width-80 margin-left-25">添加</button>
                </div>
                <div class="col-md-12">
                    <div class="js_modal_params">
                        <div class="gone jmp_node">
                            <div class="js_modal_param">
                                <div class="col-md-4 gone">
                                    <div class="form-group ">
                                        <input type="hidden" class="form-control js_mp_id" placeholder="id" >
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group ">
                                        <input type="text" class="form-control js_mp_name" placeholder="链接名称" >
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group ">
                                        <select class="form-control js_mp_target">
                                            <option value="_self">_self</option>
                                            <option value="_blank">_blank</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="form-group ">
                                        <select class="form-control js_mp_btn_type">
                                            <option value="0">自定义</option>
                                            <option value="1">单页列表</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-3  js_mp_url_sec js_mp_btn_type_target_sec">
                                    <div class="form-group ">
                                        <input type="text" class="form-control js_mp_url" placeholder="链接地址" >
                                    </div>
                                </div>

                                <div class="col-md-3 gone js_mp_page_sec js_mp_btn_type_target_sec">
                                    <div class="form-group ">
                                        <select class="form-control js_mp_page">
                                            <?php echo $pageOptionsHtml;?>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-group">
                                        <a href="javascript:;" class="btn default green js_up">
                                            <i class="fa fa-arrow-up"></i>
                                        </a>
                                        <a href="javascript:;" class="btn default  js_down">
                                            <i class="fa fa-arrow-down"></i>
                                        </a>
                                        <button type="button" class="btn red jmp_delete"><i class="icon-close"></i> 删除</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jmp_list">

                        </div>

                    </div>
                </div>
            </div>





        </div>
        <div class="modal-footer">
            <button type="button" class="btn default js_cancel" data-dismiss="modal">取消</button>
            <button type="button" class="btn blue js_submit">提交</button>
        </div>
    </div>
</div>
