<div class="page-content">
    <div class="portlet box black">
        <div class="portlet-title">
            <div class="caption">
                新闻配置
            </div>
            <div class="tools">

            </div>
            <div class="actions">
                <a href="javascript:;" class="btn btn-default btn-sm js_edit js_new_btn ">
                    <i class="fa fa-plus"></i>
                    添加新闻
                </a>
                <a href="javascript:;" class="btn btn-default btn-sm js_sort_save">
                    <i class="fa fa-save"></i> 保存排序
                </a>
            </div>
        </div>
        <div class="portlet-body" id="wrapperPageList">
<!--            <textarea  id="editor" class=" form-control" rows="20"></textarea>-->

            <div class="table-scrollable" >
                <table class="table table-striped table-bordered table-hover table-middle" align="center">
                    <thead>
                    <tr>
                        <th class="min-width-100">标题</th>
                        <th class="min-width-100">新闻时间</th>
                        <th class="min-width-100">排序</th>
                        <th >操作</th>
                    </tr>
                    </thead>
                    <tbody class="js_table_list" id="list">
                    </tbody>
                </table>
            </div>
            <div id='list_count' class="gone"></div>
            <?php echo BaseBuilder::createPageIndicator();?>
        </div>
    </div>
</div>


<div class="modal-dialog modal fade modal-scroll" id="editOrAddModal" tabindex="-1"  data-width="80%">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title" data-new="添加" data-edit="编辑"></h4>
        </div>
        <div class="modal-body ">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">标题</label>
                        <input type="text" id="js_modal_name" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">新闻时间</label>
                        <input type="text" id="js_modal_time" class="form-control" value="">
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label">新闻内容</label>
                        <textarea  id="js_modal_content" class=" form-control" rows="50"></textarea>
                    </div>
                </div>
            </div>



        </div>
        <div class="modal-footer">
            <button type="button" class="btn default js_cancel" data-dismiss="modal">取消</button>
            <button type="button" class="btn blue js_submit">提交</button>
        </div>
    </div>
</div>