<div class="page-content">
    <div class="portlet box black">
        <div class="portlet-title">
            <div class="caption">
                招聘配置
            </div>
            <div class="tools">

            </div>
            <div class="actions">
                <a href="javascript:;" class="btn btn-default btn-sm js_edit js_new_btn ">
                    <i class="fa fa-plus"></i>
                    添加职位
                </a>

            </div>
        </div>
        <div class="portlet-body" id="wrapperPageList">
            <div class="table-scrollable" >
                <table class="table table-striped table-bordered table-hover table-middle" align="center">
                    <thead>
                    <tr>
                        <th class="min-width-100">职位名称</th>
                        <th class="min-width-100">工作地点</th>
                        <th class="min-width-100">招聘人数</th>
                        <th class="min-width-100">工作经验</th>
                        <th class="min-width-100">学历要求</th>
                        <th class="min-width-100">工作性质</th>
                        <th class="min-width-100">薪资范围</th>
                        <th class="min-width-100">更新时间</th>
                        <th >操作</th>
                    </tr>
                    </thead>
                    <tbody class="js_table_list" id="list">
                    </tbody>
                </table>
            </div>
            <div id='list_count' class="gone"></div>
            <?php echo BaseBuilder::createPageIndicator();?>
        </div>
    </div>
</div>


<div class="modal-dialog modal fade modal-scroll" id="editOrAddModal" tabindex="-1"  data-width="80%">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title" data-new="添加" data-edit="编辑"></h4>
        </div>
        <div class="modal-body ">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label">职位名称</label>
                        <input type="text" id="js_modal_name" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">工作地点</label>
                        <input type="text" id="js_modal_location" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">招聘人数</label>
                        <input type="text" id="js_modal_count" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">工作经验</label>
                        <input type="text" id="js_modal_experience" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">学历要求</label>
                        <input type="text" id="js_modal_degree" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">工作性质</label>
                        <input type="text" id="js_modal_property" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">薪资范围</label>
                        <input type="text" id="js_modal_salary" class="form-control" placeholder="">
                        <span class="help-block"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label">岗位职责</label>
                        <textarea  id="js_modal_description" class="form-control" rows="10"></textarea>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="control-label">岗位要求</label>
                        <textarea  id="js_modal_requirement" class="form-control" rows="10"></textarea>
                    </div>
                </div>
            </div>



        </div>
        <div class="modal-footer">
            <button type="button" class="btn default js_cancel" data-dismiss="modal">取消</button>
            <button type="button" class="btn blue js_submit">提交</button>
        </div>
    </div>
</div>
