<?php

/**
 * Created by JetBrains PhpStorm.
 * User: xiufei lu 项目静态数据请勿删除
 * Date: 14-3-5
 * Time: 上午11:43
 * To change this template use File | Settings | File Templates.
 */
class DataApi
{
    /**
     * 获取班车统计时间表
     * @return array
     */
    public static function getBusTimeMap()
    {
        $result=array(
            'BZ001' => array(
                'shuttle'=>array(
                    '09:15'=>array(
                        'time'=>'09:15',
                    ),
                    '09:45'=>array(
                        'time'=>'09:45',
                    ),
                    '10:15'=>array(
                        'time'=>'10:15',
                    ),
                ),
                'bus'=>array(
                    '07:30'=>array(
                        'time'=>'07:30',
                    ),
                    '08:00'=>array(
                        'time'=>'08:00',
                    ),
                    '08:15'=>array(
                        'time'=>'08:15',
                    ),
                    '08:30'=>array(
                        'time'=>'08:30',
                    ),
                    '08:45'=>array(
                        'time'=>'08:45',
                    ),
                    '08:50'=>array(
                        'time'=>'08:50',
                    ),
                    '08:55'=>array(
                        'time'=>'08:55',
                    ),
                    '09:00'=>array(
                        'time'=>'09:00',
                    ),
                    '09:05'=>array(
                        'time'=>'09:05',
                    ),
                    '09:10'=>array(
                        'time'=>'09:10',
                    ),
                    '09:15'=>array(
                        'time'=>'09:15',
                    ),
                    '10:00'=>array(
                        'time'=>'10:00',
                    ),
                )
            ),
            'BZ002' => array(
                'bus'=>array(
                    '08:30'=>array(
                        'time'=>'08:30',
                    ),
                    '09:00'=>array(
                        'time'=>'09:00',
                    ),
                    '09:30'=>array(
                        'time'=>'09:30',
                    ),
                    '10:00'=>array(
                        'time'=>'10:00',
                    ),
                    '10:30'=>array(
                        'time'=>'10:30',
                    )
                )
            ),
            'BZ003' => array(
                'bus'=>array(
                    '08:10'=>array(
                        'time'=>'08:10',
                    ),
                    '08:30'=>array(
                        'time'=>'08:30',
                    ),
                    '08:50'=>array(
                        'time'=>'08:50',
                    ),
                    '09:10'=>array(
                        'time'=>'09:10',
                    ),
                    '09:20'=>array(
                        'time'=>'09:20',
                    ),
                    '09:30'=>array(
                        'time'=>'09:30',
                    )
                )
            ),
            'BZ004' => array(
                'bus'=>array(
                    '08:10'=>array(
                        'time'=>'08:10',
                    ),
                    '08:30'=>array(
                        'time'=>'08:30',
                    ),
                    '08:40'=>array(
                        'time'=>'08:40',
                    ),
                    '08:50'=>array(
                        'time'=>'08:50',
                    ),
                    '09:00'=>array(
                        'time'=>'09:00',
                    ),
                    '09:10'=>array(
                        'time'=>'09:10',
                    ),
                    '09:20'=>array(
                        'time'=>'09:20',
                    ),
                    '09:25'=>array(
                        'time'=>'09:25',
                    ),
                    '09:30'=>array(
                        'time'=>'09:30',
                    )
                )
            ),
            'BZ005' => array(
                'bus'=>array(
                    '08:30'=>array(
                        'time'=>'08:30',
                    ),
                    '08:50'=>array(
                        'time'=>'08:50',
                    ),
                    '09:00'=>array(
                        'time'=>'09:00',
                    ),
                    '09:10'=>array(
                        'time'=>'09:10',
                    ),
                    '09:20'=>array(
                        'time'=>'09:20',
                    ),
                    '09:25'=>array(
                        'time'=>'09:25',
                    ),
                    '09:30'=>array(
                        'time'=>'09:30',
                    )
                )
            ),

            'BW001' => array(
                'bus'=>array(
                    '18:00'=>array(
                        'time'=>'18:00',
                    ),
                    '18:10'=>array(
                        'time'=>'18:10',
                    ),
                    '18:20'=>array(
                        'time'=>'18:20',
                    ),
                    '18:30'=>array(
                        'time'=>'18:30',
                    ),
                    '18:40'=>array(
                        'time'=>'18:40',
                    ),
                    '18:50'=>array(
                        'time'=>'18:50',
                    ),
                    '19:00'=>array(
                        'time'=>'19:00',
                    ),
                    '19:10'=>array(
                        'time'=>'19:10',
                    ),
                    '19:20'=>array(
                        'time'=>'19:20',
                    ),
                    '19:30'=>array(
                        'time'=>'19:30',
                    ),
                    '19:40'=>array(
                        'time'=>'19:40',
                    ),
                    '19:50'=>array(
                        'time'=>'19:50',
                    ),
                )
            ),
            'BW002' => array(
                'bus'=>array(
                    '18:30'=>array(
                        'time'=>'18:30',
                    ),
                    '19:00'=>array(
                        'time'=>'19:00',
                    ),
                    '19:30'=>array(
                        'time'=>'19:30',
                    ),
                    '20:00'=>array(
                        'time'=>'20:00',
                    ),
                    '21:30'=>array(
                        'time'=>'21:30',
                    ),
                    '22:00'=>array(
                        'time'=>'22:00',
                    )
                )
            ),
            'BW003' => array(
                'bus'=>array(
                    '18:00'=>array(
                        'time'=>'18:00',
                    ),
                    '18:20'=>array(
                        'time'=>'18:20',
                    ),
                    '18:40'=>array(
                        'time'=>'18:40',
                    ),
                    '19:00'=>array(
                        'time'=>'19:00',
                    ),
                    '19:20'=>array(
                        'time'=>'19:20',
                    ),
                    '19:40'=>array(
                        'time'=>'19:40',
                    ),
                    '20:30'=>array(
                        'time'=>'20:30',
                    ),
                    '21:00'=>array(
                        'time'=>'21:00',
                    ),
                    '21:30'=>array(
                        'time'=>'21:30',
                    )

                )
            ),
            'BW004' => array(
                'bus'=>array(
                    '17:45'=>array(
                        'time'=>'17:45',
                    ),
                    '18:00'=>array(
                        'time'=>'18:00',
                    ),
                    '18:10'=>array(
                        'time'=>'18:10',
                    ),
                     '18:20'=>array(
                        'time'=>'18:20',
                    ),
                     '18:30'=>array(
                        'time'=>'18:30',
                    ),
                     '18:40'=>array(
                        'time'=>'18:40',
                    ),
                     '18:50'=>array(
                        'time'=>'18:50',
                    ),
                    '19:00'=>array(
                        'time'=>'19:00',
                    ),
                    '19:10'=>array(
                        'time'=>'19:10',
                    ),
                    '19:20'=>array(
                        'time'=>'19:20',
                    ),
                    '19:30'=>array(
                        'time'=>'19:30',
                    ),
                )
            ),
            'BW005' => array(
                'bus'=>array(
                    '18:00'=>array(
                        'time'=>'18:00',
                    ),
                    '18:15'=>array(
                        'time'=>'18:15',
                    ),
                    '18:30'=>array(
                        'time'=>'18:30',
                    ),
                    '18:45'=>array(
                        'time'=>'18:45',
                    ),
                    '18:50'=>array(
                        'time'=>'18:50',
                    ),
                    '19:00'=>array(
                        'time'=>'19:00',
                    ),
                    '19:15'=>array(
                        'time'=>'19:15',
                    ),
                    '19:30'=>array(
                        'time'=>'19:30',
                    ),
                    '19:45'=>array(
                        'time'=>'19:45',
                    ),
                    '20:00'=>array(
                        'time'=>'20:00',
                    ),
                    '20:20'=>array(
                        'time'=>'20:20',
                    ),
                    '20:40'=>array(
                        'time'=>'20:40',
                    ),
                    '21:00'=>array(
                        'time'=>'21:00',
                    ),
                    '21:30'=>array(
                        'time'=>'21:30',
                    ),
                    '22:00'=>array(
                        'time'=>'22:00',
                    ),
                )
            ),
        );
        return $result;
    }

}