<div class="page-content">
    <div class="portlet box black">
        <div class="portlet-title">
            <div class="caption">
<!--                <i class="icon-wrench"></i>-->
                合作伙伴
            </div>
            <div class="tools">

            </div>
            <div class="actions">
                <a href="javascript:;" class="btn btn-default btn-sm js_edit js_new_btn ">
                    <i class="fa fa-plus"></i>
                    添加合作伙伴
                </a>

            </div>
        </div>
        <div class="portlet-body">
            <div class="table-scrollable">
                <table class="table table-striped table-bordered table-hover" align="center">
                    <thead>
                    <tr>
                        <th class="min-width-100">logo</th>
                        <th class="min-width-100">跳转链接</th>
                        <th >操作</th>
                    </tr>
                    </thead>
                    <tbody class="js_table_list">
                    <?php echo $this->html;?>
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>


<div class="modal-dialog modal fade modal-scroll" id="editOrAddModal" tabindex="-1"  >
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title" data-new="添加" data-edit="编辑"></h4>
        </div>
        <div class="modal-body ">
            <div class="form-group">
                <label for="message-text" class="control-label">跳转链接</label>
                <input type="text" class="form-control" id="js_modal_url">
            </div>
            <div class="form-group gone">
                <label for="message-text" class="control-label">logo</label>
                <input type="text" class="form-control" id="js_modal_img">
            </div>
            <div class="form-group">
                <label for="message-text" class="control-label">logo</label>
                <button type="button" class="js_upload_image btn green form-control">上传图片</button>

                <div class="gone js_progress_section">
                    <p class="size">上传中</p>
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                        <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                    </div>
                </div>
                <img class="js_img_preview img-preview gone margin-top-20" src="" >
            </div>


        </div>
        <div class="modal-footer">
            <button type="button" class="btn default cancel_button" data-dismiss="modal">取消</button>
            <button type="button" class="btn blue submit">提交</button>
        </div>
    </div>
</div>
