<div class="page-content">
    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN ROW -->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN CHART PORTLET-->
                    <div class="portlet light bordered">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="icon-bar-chart font-green-haze"></i>
                                <span class="caption-subject bold uppercase font-green-haze"> 访问统计</span>
                                <span class="caption-helper"></span>
                            </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse">
                                </a>
                                </a>
                                <a href="javascript:;" class="fullscreen">
                                </a>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <div class="row form-group">

                                <div class="col-md-4">
                                    <label class="control-label">开始时间</label>
                                    <div class="input-icon">
                                        <i class="fa fa-calendar"></i>
                                        <input id="start_search_time"  class="form-control date-picker" size="16" type="text" value="<?php echo date('Y-m-d',strtotime('-1 day'))?>" data-date-format="yyyy-mm-dd"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label class="control-label">结束时间</label>
                                    <div class="input-icon">
                                        <i class="fa fa-calendar"></i>
                                        <input id="end_search_time"  class="form-control date-picker" size="16" type="text" value="<?php echo date('Y-m-d',strtotime('-1 day'))?>" data-date-format="yyyy-mm-dd"/>
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <label class="control-label">&nbsp;</label>
                                    <div class="input-icon">
                                        <button id="search_submit" class="btn blue btn-block ">搜索 <i class="m-icon-swapright m-icon-white"></i></button>
                                    </div>
                                </div>
                            </div>
<!--                            <div id="chart_bar_user" class="chart" style="height: 500px;">-->
<!---->
<!--                            </div>-->
                            <div class="portlet-body js_piece_charts_section ">
                            </div>

                        </div>


                    </div>
                    <!-- END CHART PORTLET-->
                </div>
            </div>
            <!-- END ROW -->

        </div>
    </div>
    <!--     显示多个图表      -->
<!--    <div class="portlet-body js_piece_charts_section ">-->

<!--    </div>-->
    <!-- END PAGE CONTENT-->
</div>
<script src="/assets/global/plugins/amcharts/amcharts/amcharts.js" type="text/javascript"></script>

