<div class="page-content">

    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN ROW -->
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN CHART PORTLET-->
                    <div class="portlet light bordered" style="text-align: center">
                        <!--            <div class="portlet-title">-->
                        <!--                <div class="caption">-->
                        <!--                    <i class="icon-bar-chart font-green-haze"></i>-->
                        <!--                    <span class="caption-subject bold uppercase font-green-haze"> 注册用户统计</span>-->
                        <!--                    <span class="caption-helper"></span>-->
                        <!--                </div>-->
                        <!--                <div class="tools">-->
                        <!--                    <a href="javascript:;" class="collapse">-->
                        <!--                    </a>-->
                        <!--                    </a>-->
                        <!--                    <a href="javascript:;" class="fullscreen">-->
                        <!--                    </a>-->
                        <!--                </div>-->
                        <!--            </div>-->
                        <div class="portlet-body">
                            <img src="/images/maintain.jpg" height="500" style="margin: 0 auto;">
                        </div>
                    </div>
                    <!-- END CHART PORTLET-->
                </div>
            </div>
            <!-- END ROW -->

        </div>
    </div>
    <!-- END PAGE CONTENT-->
</div>
<script src="/assets/global/plugins/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
