<div class="modal-dialog modal fade modal-scroll" id="global_confirm_modal" tabindex="-1" role="global_confirm_modal" >
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">提示</h4>
            </div>
            <div class="modal-body">
                提示
            </div>
            <div class="modal-footer">
                <button type="button" class="btn default cancel_button" data-dismiss="modal">取消</button>
                <button type="button" class="btn blue confirm_button">确定</button>
            </div>
        </div>
        <!-- /.modal-content -->
    <!-- /.modal-dialog -->
</div>
<div class="modal-dialog modal fade modal-scroll" id="global_login_modal" tabindex="-1" role="global_login_modal" >
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
            <h4 class="modal-title">登录超时，请重新登录</h4>
        </div>
        <div class="modal-body">
            <div class="portlet-body">
                <div class="form-body">
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="text" class="form-control" id="glm_name">
                        <label for="form_control_1">用户名</label>
                        <span class="help-block">请输入用户名</span>
                    </div>
                    <div class="form-group form-md-line-input form-md-floating-label">
                        <input type="password" class="form-control" id="glm_password">
                        <label for="form_control_1">密码</label>
                        <span class="help-block">请输入密码</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn default cancel_button" data-dismiss="modal">取消</button>
            <button type="button" class="btn blue confirm_button">登录</button>
        </div>
    </div>
    <!-- /.modal-content -->
    <!-- /.modal-dialog -->
</div>