<!-- BEGIN FOOTER -->
<div class="page-footer hidden-xs">
    <div class="page-footer-inner">

    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>
<!-- END FOOTER -->

<!--global dialog pages start-->
<?php
    echo $this->partial('dialog/dialog-edit-password.phtml');
?>
<!--global dialog pages end-->


<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->

<!-- BEGIN CORE PLUGINS -->

<!--[if lt IE 9]>
<script src="/assets/global/plugins/respond.min.js"></script>
<script src="/assets/global/plugins/excanvas.min.js"></script>
<![endif]-->

<?php echo  BaseBuilder::toRequireJsHtml() ?>
