<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top position-fixed">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner">

    <!-- BEGIN LOGO -->
    <div class="page-logo">
<!--        <img src="/images/logo.jpg"  alt="" class="hl-logo" />-->
        <a href="/" class="logo-default ">
            <span style="color: #fff;">
               管理后台
            </span>
        </a>
        <div class="menu-toggler sidebar-toggler hide">
        </div>
    </div>
    <!-- END LOGO -->

    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <!-- END RESPONSIVE MENU TOGGLER -->

    <!-- BEGIN TOP NAVIGATION MENU -->
    <div class="top-menu">
    <ul class="nav navbar-nav pull-right">

    <!-- BEGIN USER LOGIN DROPDOWN -->

    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
    <li class="dropdown dropdown-user  hidden-xs">
        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
<!--            <img alt="" class="img-circle" src="/assets/admin/layout/img/avatar2.jpg"/>-->
                <span class="username username-hide-on-mobile">
                    <?php
                        $info=HolloEnv::getUserInfo();
                        echo $info['name'];
                    ?>
                </span>
            <i class="fa fa-angle-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-menu-default">
            <li>
                <a class="globalEditPassword">
                    <i class="icon-user"></i>
                    修改密码
                </a>
            </li>
            <li class="divider"></li>
            <li class="">
                <a href="/index/logout">
                    <i class="icon-key"></i>退出 </a>
            </li>
        </ul>
    </li>
    <!-- END USER LOGIN DROPDOWN -->

    <!-- BEGIN QUICK SIDEBAR TOGGLER -->
    <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
<!--    <li class="dropdown dropdown-quick-sidebar-toggler ">-->
<!--        <a href="/index/logout" class="dropdown-toggle">-->
<!--            <i class="icon-logout"></i>-->
<!--        </a>-->
<!--    </li>-->
    <!-- END QUICK SIDEBAR TOGGLER -->

    </ul>
    </div>
    <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

<div class="clearfix"></div>